### ISSUE TITLE
真的有基岩版服务器上GitHub了?

### ISSUE THREAD

**Issue by qianxliu** [FuturecraftServer/mainsite#1]
看是唯一一个<br>
网站内容显示还是有点少

**Comment by qianxliu** [comment]
建议建一个discord群组，这个是网页版的QQ，比论坛更强大，就是国内有点卡，其他都好，还能传文件等

**Comment by qianxliu** [comment]
但是服务器好像进不去……

**Comment by qianxliu** [comment]
@kengwang

**Comment by kengwang** [comment]
我在备战中考，暂时关服，7月24日再次开服。届时会有很多新功能！

**Comment by kengwang** [comment]
> 建议建一个discord群组，这个是网页版的QQ，比论坛更强大，就是国内有点卡，其他都好，还能传文件等

感谢建议，我到时候会做的

**Comment by qianxliu** [comment]
厉害👍

**Comment by qianxliu** [comment]
如果能做的好的话可以邀请我吗，我可以贡献Android方面的代码，是国内基岩版GitHub第一人了，如果继续做下去以后成为国内最大的基岩服务器也不一定的吧

**Comment by qianxliu** [comment]
先关issue了

**Comment by qianxliu** [comment]
还是先打开以看消息

**Comment by kengwang** [comment]
感谢支持！
开个Github的团队账户主要是为了方便管理服务器插件已经白嫖个Github Pages
服务器目前还在初级阶段，也没有多少人 （2020.3.14 创建的服务器），暑假时我会建设这个服务器的

**Comment by kengwang** [comment]
本服务器主要还是搞的原版生存，在此基础上搞一些杂七杂八的东西，等玩家多起来了也会搞一些建筑赛之类的
开这个服我坚持两个原则：
1. 只用BDS端，以给玩家原版一致的体验
2. 插件自主开发（目前托管于Github 一个 Private项目，时机成熟将会开源）

**Comment by qianxliu** [comment]
中考生，是我辈榜样👍
